from setuptools import setup, find_packages

setup(
    name="bookmark_summarizer",
    version="1.0.0",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "httpx>=0.25.0",
        "beautifulsoup4>=4.12.0",
        "openai>=1.3.0",
        "python-dotenv>=1.0.0",
        "aiofiles>=23.2.0",
        "pydantic>=2.0.0",
        "mermaid-py>=0.4.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.0.0",
            "pytest-asyncio>=0.21.0",
            "pytest-cov>=4.0.0",
            "pytest-mock>=3.10.0",
            "responses>=0.24.0",
            "mypy>=1.5.0",
            "ruff>=0.1.0",
            "black>=23.0.0",
            "isort>=5.12.0",
            "flake8>=6.0.0",
            "pylint>=2.17.0",
        ],
    },
    author="Kan Software",
    author_email="contact@kansoftware.dev",
    description="Утилита для экспорта и описания закладок браузера с использованием LLM",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/kansoftware/BookmarksReview",
    project_urls={
        "Bug Reports": "https://github.com/kansoftware/BookmarksReview/issues",
        "Source": "https://github.com/kansoftware/BookmarksReview",
        "Documentation": "https://github.com/kansoftware/BookmarksReview#readme",
    },
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Developers",
        "Intended Audience :: End Users/Desktop",
        "Topic :: Internet :: WWW/HTTP",
        "Topic :: Text Processing :: Markup :: Markdown",
        "Topic :: Utilities",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Operating System :: OS Independent",
        "Framework :: AsyncIO",
    ],
    keywords="bookmarks, chrome, browser, export, markdown, llm, openai, summarization, mermaid",
    python_requires=">=3.9",
    entry_points={
        "console_scripts": [
            "bookmark_summarizer=src.main:main",
        ],
    },
    include_package_data=True,
    zip_safe=False,
)